# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lora_finetuning.transport import service_pb2 as lora__finetuning_dot_transport_dot_service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lora_finetuning/transport/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestAdapter = channel.unary_stream(
                '/lora_adapter.AdapterService/GetLatestAdapter',
                request_serializer=lora__finetuning_dot_transport_dot_service__pb2.GetLatestRequest.SerializeToString,
                response_deserializer=lora__finetuning_dot_transport_dot_service__pb2.AdapterChunk.FromString,
                _registered_method=True)


class AdapterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestAdapter(self, request, context):
        """Client-driven pull: return the current adapter if it is strictly newer than
        have_version, else an empty stream. The client calls this on its own schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestAdapter': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLatestAdapter,
                    request_deserializer=lora__finetuning_dot_transport_dot_service__pb2.GetLatestRequest.FromString,
                    response_serializer=lora__finetuning_dot_transport_dot_service__pb2.AdapterChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lora_adapter.AdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lora_adapter.AdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lora_adapter.AdapterService/GetLatestAdapter',
            lora__finetuning_dot_transport_dot_service__pb2.GetLatestRequest.SerializeToString,
            lora__finetuning_dot_transport_dot_service__pb2.AdapterChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
