# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lora_finetuning/common/transport/service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'lora_finetuning/common/transport/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.lora_finetuning/common/transport/service.proto\x12\x0clora_adapter\"(\n\x10GetLatestRequest\x12\x14\n\x0chave_version\x18\x01 \x01(\x05\"\x8c\x01\n\x0b\x41\x64\x61pterMeta\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04step\x18\x02 \x01(\x03\x12\x0c\n\x04loss\x18\x03 \x01(\x01\x12\x10\n\x08has_loss\x18\x04 \x01(\x08\x12\x14\n\x0cpublished_at\x18\x05 \x01(\x01\x12\x13\n\x0b\x63onfig_json\x18\x06 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x07 \x01(\x03\"V\n\x0c\x41\x64\x61pterChunk\x12\'\n\x04meta\x18\x01 \x01(\x0b\x32\x19.lora_adapter.AdapterMeta\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x0c\n\x04last\x18\x03 \x01(\x08\x32\x62\n\x0e\x41\x64\x61pterService\x12P\n\x10GetLatestAdapter\x12\x1e.lora_adapter.GetLatestRequest\x1a\x1a.lora_adapter.AdapterChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lora_finetuning.common.transport.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLATESTREQUEST']._serialized_start=64
  _globals['_GETLATESTREQUEST']._serialized_end=104
  _globals['_ADAPTERMETA']._serialized_start=107
  _globals['_ADAPTERMETA']._serialized_end=247
  _globals['_ADAPTERCHUNK']._serialized_start=249
  _globals['_ADAPTERCHUNK']._serialized_end=335
  _globals['_ADAPTERSERVICE']._serialized_start=337
  _globals['_ADAPTERSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
